---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: contrail
  name: rabbitmq
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: contrail
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
