apiVersion: v1
kind: Pod
metadata:
  namespace: contrail
  name: centos
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh","-c", "while true; do echo hello; sleep 10;done"]
