---
apiVersion: v1
kind: Service
metadata:
  name: contrailcontrol-svc
  labels:
    app: contrailcontrol-svc
spec:
  ports:
  - port: 5269
    targetPort: 5269
    protocol: TCP
    name: xmpp
  - port: 179
    targetPort: 179
    protocol: TCP
    name: bgp
  type: NodePort
  selector:
    app: contrailcontrol
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: contrailcontrol-pdb
spec:
  selector:
    matchLabels:
      app: contrailcontrol
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: contrailcontrol
spec:
  serviceName: contrailcontrol-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: contrailcontrol
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - contrailcontrol
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: contrail_dns
        emptyDir: {}
      containers:
      - name: nodemgr
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-nodemgr:queens-master-118-centos
        command: ["/bin/sh","-c", "while true; do echo hello; sleep 10;done"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: contrail-cm
        env:
        - name: NODE_TYPE
          value: "control"
      - name: control
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-control-control:queens-master-118-centos
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          name: client
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: named
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-control-named:queens-master-118-centos
        privileged: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        hostPID: true
        envFrom:
        - configMapRef:
            name: contrail-cm
        volumeMounts:
        - name: contrail_dns
          mountPath: /etc/contrail/dns
      - name: dns
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-control-dns:queens-master-118-centos
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        hostPID: true
        envFrom:
        - configMapRef:
            name: contrail-cm
        volumeMounts:
        - name: contrail_dns
          mountPath: /etc/contrail/dns
