---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-cm
data:
        #ANALYTICS_SERVERS: "contrailanalytics-svc:8081"
        #COLLECTOR_SERVERS: "contrailanalytics-svc:8086"
  ANALYTICS_NODES: "contrailanalytics-0.contrailanalytics-svc,contrailanalytics-1.contrailanalytics-svc,contrailanalytics-2.contrailanalytics-svc"
  #CONFIG_SERVERS: "contrailconfig-svc:8082"
  CONFIG_NODES: "contrailconfig-0.contrailconfig-svc,contrailconfig-1.contrailconfig-svc,contrailconfig-2.contrailconfig-svc"
  ANALYTICSDB_CQL_PORT: "9042"
  ANALYTICSDB_NODES: "cassandra-0.cassandra,cassandra-1.cassandra,cassandra-2.cassandra"
  ANALYTICSDB_PORT: "9160"
  CASSANDRA_JMX_LOCAL_PORT: "7200"
  CLOUD_ORCHESTRATOR: "kubernetes"
  CONFIGDB_NODES: "cassandra-0.cassandra,cassandra-1.cassandra,cassandra-2.cassandra"
  CONFIGDB_PORT: "9160"
  CONFIGDB_CQL_PORT: "9042"
  IPFABRIC_SERVICE_HOST: "contrailconfig-0.contrailconfig-svc"
  RABBITMQ_NODE_PORT: "5672"
  RABBITMQ_NODES: "rabbitmq-0.rabbitmq,rabbitmq-1.rabbitmq,rabbitmq-2.rabbitmq"
  ZOOKEEPER_ANALYTICS_NODES: "zk-0.zk-svc,zk-1.zk-svc,zk-2.zk-svc"
  ZOOKEEPER_ANALYTICS_PORT: "2181"
  ZOOKEEPER_NODES: "zk-0.zk-svc,zk-1.zk-svc,zk-2.zk-svc"
  KAFKA_NODES: "kafka-0.kafka-svc,kafka-1.kafka-svc,kafka-2.kafka-svc"
  CONTRAIL_CONTAINER_REGISTRY: docker.io/michaelhenkel
  CONTRAIL_CONTAINER_TAG: queens-5.0.2-dev
