---
apiVersion: v1
kind: Service
metadata:
  name: contrailanalytics-svc
  labels:
    app: contrailanalytics-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: api
  type: LoadBalancer
  selector:
    app: contrailanalytics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrailanalytics-cm
data:
  RABBITMQ_NODE_PORT: "5672"
  ANALYTICSDB_PORT: "9160"
  ANALYTICSDB_CQL_PORT: "9042"
  ZOOKEEPER_ANALYTICS_PORT: "2181"
  CONFIG_NODES: "contrailconfig-0.contrailconfig-svc.default.svc.cluster.local,contrailconfig-1.contrailconfig-svc.default.svc.cluster.local,contrailconfig-2.contrailconfig-svc.default.svc.cluster.local"
  ANALYTICS_NODES: "contrailanalytics-0.contrailanalytics-svc.default.svc.cluster.local,contrailanalytics-1.contrailanalytics-svc.default.svc.cluster.local,contrailanalytics-2.contrailanalytics-svc.default.svc.cluster.local"
  ANALYTICSDB_NODES: "cassandra-0.cassandra.default.svc.cluster.local,cassandra-1.cassandra.default.svc.cluster.local,cassandra-2.cassandra.default.svc.cluster.local"
  ZOOKEEPER_ANALYTICS_NODES: "zk-0.zk-svc.default.svc.cluster.local,zk-1.zk-svc.default.svc.cluster.local,zk-2.zk-svc.default.svc.cluster.local"
  RABBITMQ_NODES: "rabbitmq-0.rabbitmq.default.svc.cluster.local,rabbitmq-1.rabbitmq.default.svc.cluster.local,rabbitmq-2.rabbitmq.default.svc.cluster.local"
  CLOUD_ORCHESTRATOR: kubernetes
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: contrailanalytics-pdb
spec:
  selector:
    matchLabels:
      app: contrailanalytics
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: contrailanalytics
spec:
  serviceName: contrailanalytics-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: contrailanalytics
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - contrailanalytics
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: api
        imagePullPolicy: Always
        image: docker.io/opencontrailnightly/contrail-analytics-api:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          name: client
        env:
        - name : RABBITMQ_NODE_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODE_PORT
        - name : ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICS_NODES
        - name : CONFIG_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: CONFIG_NODES
        - name : ANALYTICSDB_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_NODES
        - name : ZOOKEEPER_ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_NODES
        - name : RABBITMQ_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODES
        - name : ANALYTICSDB_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_PORT
        - name : ANALYTICSDB_CQL_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_CQL_PORT
        - name : ZOOKEEPER_ANALYTICS_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_PORT
      - name: collector
        imagePullPolicy: Always
        image: docker.io/opencontrailnightly/contrail-analytics-collector:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name : RABBITMQ_NODE_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODE_PORT
        - name : ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICS_NODES
        - name : CONFIG_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: CONFIG_NODES
        - name : ANALYTICSDB_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_NODES
        - name : ZOOKEEPER_ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_NODES
        - name : RABBITMQ_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODES
        - name : ANALYTICSDB_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_PORT
        - name : ANALYTICSDB_CQL_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_CQL_PORT
        - name : ZOOKEEPER_ANALYTICS_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_PORT
      - name: query-engine
        imagePullPolicy: Always
        image: docker.io/opencontrailnightly/contrail-analytics-query-engine:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name : RABBITMQ_NODE_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODE_PORT
        - name : ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICS_NODES
        - name : CONFIG_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: CONFIG_NODES
        - name : ANALYTICSDB_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_NODES
        - name : ZOOKEEPER_ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_NODES
        - name : RABBITMQ_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODES
        - name : ANALYTICSDB_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_PORT
        - name : ANALYTICSDB_CQL_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_CQL_PORT
        - name : ZOOKEEPER_ANALYTICS_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_PORT
      - name: alarm-gen
        imagePullPolicy: Always
        image: docker.io/opencontrailnightly/contrail-analytics-alarm-gen:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name : RABBITMQ_NODE_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODE_PORT
        - name : ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICS_NODES
        - name : CONFIG_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: CONFIG_NODES
        - name : ANALYTICSDB_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_NODES
        - name : ZOOKEEPER_ANALYTICS_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_NODES
        - name : RABBITMQ_NODES
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: RABBITMQ_NODES
        - name : ANALYTICSDB_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_PORT
        - name : ANALYTICSDB_CQL_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ANALYTICSDB_CQL_PORT
        - name : ZOOKEEPER_ANALYTICS_PORT
          valueFrom:
            configMapKeyRef:
                name: contrailanalytics-cm
                key: ZOOKEEPER_ANALYTICS_PORT
