---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: contrail
  name: contrail-cm
data:
  CASSANDRA_SEEDS: "cassandra-0.cassandra.contrail.svc.cluster.local"
  ANALYTICS_NODES: "contrailanalytics-0.contrailanalytics-svc.contrail.svc.cluster.local,contrailanalytics-1.contrailanalytics-svc.contrail.svc.cluster.local,contrailanalytics-2.contrailanalytics-svc.contrail.svc.cluster.local"
  CONFIG_NODES: "contrailconfig-0.contrailconfig-svc.contrail.svc.cluster.local,contrailconfig-1.contrailconfig-svc.contrail.svc.cluster.local,contrailconfig-2.contrailconfig-svc.contrail.svc.cluster.local"
  CONTROL_NODES: "contrailcontrol-0.contrailcontrol-svc.contrail.svc.cluster.local,contrailcontrol-1.contrailcontrol-svc.contrail.svc.cluster.local,contrailcontrol-2.contrailcontrol-svc.contrail.svc.cluster.local"
  ANALYTICSDB_CQL_PORT: "9042"
  ANALYTICSDB_NODES: "cassandra-0.cassandra.contrail.svc.cluster.local,cassandra-1.cassandra.contrail.svc.cluster.local,cassandra-2.cassandra.contrail.svc.cluster.local"
  ANALYTICSDB_PORT: "9160"
  CASSANDRA_JMX_LOCAL_PORT: "7200"
  CLOUD_ORCHESTRATOR: "kubernetes"
  CONFIGDB_NODES: "cassandra-0.cassandra.contrail.svc.cluster.local,cassandra-1.cassandra.contrail.svc.cluster.local,cassandra-2.cassandra.contrail.svc.cluster.local"
  CONFIGDB_PORT: "9160"
  CONFIGDB_CQL_PORT: "9042"
  IPFABRIC_SERVICE_HOST: "contrailconfig-0.contrailconfig-svc.contrail.svc.cluster.local"
  RABBITMQ_NODE_PORT: "5672"
  RABBITMQ_NODES: "rabbitmq-0.rabbitmq.contrail.svc.cluster.local,rabbitmq-1.rabbitmq.contrail.svc.cluster.local,rabbitmq-2.rabbitmq.contrail.svc.cluster.local"
  ZOOKEEPER_ANALYTICS_NODES: "zk-0.zk-svc,zk-1.zk-svc,zk-2.zk-svc"
  ZOOKEEPER_ANALYTICS_PORT: "2181"
  ZOOKEEPER_NODES: "zk-0.zk-svc.contrail.svc.cluster.local,zk-1.zk-svc.contrail.svc.cluster.local,zk-2.zk-svc.contrail.svc.cluster.local"
  KAFKA_NODES: "kafka-0.kafka-svc.contrail.svc.cluster.local,kafka-1.kafka-svc.contrail.svc.cluster.local,kafka-2.kafka-svc.contrail.svc.cluster.local"
  CONTRAIL_CONTAINER_REGISTRY: docker.io/michaelhenkel
  CONTRAIL_CONTAINER_TAG: 5.1-dev1
