---
apiVersion: v1
kind: Service
metadata:
  name: contrailconfig-svc
  labels:
    app: contrailconfig-svc
spec:
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: api
  clusterIP: None
  selector:
    app: contrailconfig
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: contrailconfig-pdb
spec:
  selector:
    matchLabels:
      app: contrailconfig
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: contrailconfig
spec:
  serviceName: contrailconfig-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: contrailconfig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - contrailconfig
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: contrail-nightly
      containers:
      - name: nodemgr
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-nodemgr:queens-5.0.2-dev
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
        env:
        - name: NODE_TYPE
          value: "config"
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
        volumeMounts:
        - mountPath: /mnt
          name: docker-unix-socket
      - name: api
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-api:queens-5.0.2-dev
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8082
          name: client
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: svcmonitor
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-svcmonitor:queens-5.0.2-dev
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: schema
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-schema:queens-5.0.2-dev
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: devicemgr
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-devicemgr:queens-5.0.2-dev
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
      - name: host-usr-bin
        hostPath:
          path: /usr/bin
