---
apiVersion: v1
kind: Service
metadata:
  name: contrailconfig-svc
  labels:
    app: contrailconfig-svc
spec:
  ports:
  - port: 8082
    name: api
  clusterIP: None
  selector:
    app: contrailconfig
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: contrailconfig-pdb
spec:
  selector:
    matchLabels:
      app: contrailconfig
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: contrailconfig
spec:
  serviceName: contrailconfig-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: contrailconfig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - contrailconfig
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nodemgr
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-nodemgr:queens-master-118-centos
        command: ["/bin/sh","-c", "while true; do echo hello; sleep 10;done"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
        env:
        - name: NODE_TYPE
          value: "config"
      - name: api
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-api:queens-master-118-centos
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8082
          name: client
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: svcmonitor
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-svcmonitor:queens-master-118-centos
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: schema
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-schema:queens-master-118-centos
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: devicemgr
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-config-devicemgr:queens-master-118-centos
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
