---
apiVersion: v1
kind: Service
metadata:
  namespace: contrail
  name: contrailwebui-svc
  labels:
    app: contrailwebui-svc
spec:
#  externalTrafficPolicy: Local
#  type: NodePort
#  ports:
#  - port: 8143
#    nodePort: 31443
#    name: webui
spec:
  ports:
  - port: 8143
    targetPort: 8143
    protocol: TCP
    name: webui
  externalIPs:
  - 192.168.1.100
#  type: ClusterIP
  selector:
    app: contrailwebui
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: contrail
  name: contrailwebui-pdb
spec:
  selector:
    matchLabels:
      app: contrailwebui
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: contrail
  name: contrailwebui
spec:
  serviceName: contrailwebui-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: contrailwebui
    spec:
#      dnsPolicy: ClusterFirstWithHostNet
#      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - contrailwebui
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis
        imagePullPolicy: Always
        image: docker.io/redis:4.0.2
        ports:
        - containerPort: 6379
          name: client
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
      - name: web
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-webui-web:5.1-dev1
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8143
          name: client
        envFrom:
        - configMapRef:
            name: contrail-cm
      - name: job
        imagePullPolicy: Always
        image: docker.io/michaelhenkel/contrail-controller-webui-job:5.1-dev1
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: contrail-cm
