---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: contrail
  name: rabbitmq 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: contrail
  name: endpoint-reader
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: contrail
  name: endpoint-reader
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: contrail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
