---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kafka
spec:
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      serviceAccountName: contrail-service-account
      initContainers:
        - name: init-myservice
          image: {{ .Values.global.containerRegistry }}/contrail-init:{{ .Values.global.containerTag }}
          command: ["/app"]
      containers:
      - name: kafka
        image: "{{ .Values.global.containerRegistry }}/contrail-external-kafka:{{ .Values.global.containerTag }}"
        imagePullPolicy: ""
        env:
        - name: NODE_TYPE
          value: database
        - name: ZOOKEEPER_ANALYTICS_PORT
          value: "2181"
        - name: CONTROLLER_NODES
          valueFrom:
            configMapKeyRef:
              name: contrailcontrollernodes
              key: CONTROLLER_NODES
