---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql-svc
    - port: 9160
      name: rpc-svc
  selector:
    app: cassandra
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: {{ .Values.global.namespace }}
#  name: cassandra-data-1
#  labels:
#    type: local
#    app: cassandra
#spec:
#  capacity:
#    storage: 20Gi
#  accessModes:
##    - ReadWriteOnce
#  hostPath:
#    path: /tmp/data/cassandra-data-1
#  persistentVolumeReclaimPolicy: Delete
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: {{ .Values.global.namespace }}
#  name: cassandra-data-2
#  labels:
#    type: local
#    app: cassandra
#spec:
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /tmp/data/cassandra-data-2
#  persistentVolumeReclaimPolicy: Delete
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: {{ .Values.global.namespace }}
#  name: cassandra-data-3
#  labels:
#    type: local
#    app: cassandra
#spec:
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /tmp/data/cassandra-data-3
#  persistentVolumeReclaimPolicy: Delete
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  namespace: {{ .Values.global.namespace }}
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra
        "net.juniper.contrail.service": "cassandra"
        "net.juniper.contrail.container.name": "contrail-external-cassandra"
    spec:
      containers:
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: rpc
          envFrom:
            - configMapRef:
                name: contrail-cm
          env:
            - name: MAX_HEAP_SIZE
              value: 2048M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
        annotations:  # comment line if you want to use a StorageClass
          # or specify which StorageClass
          #volume.beta.kubernetes.io/storage-class: ""   # comment line if you
          # want to use a StorageClass or specify which StorageClass
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi

